- name: Copy jenkins job dockerfile maven file
  template:
    src: Dockerfile.maven.j2
    dest: /home/{{ username }}/jenkins/slaves/Dockerfile.maven

- name: Copy jenkins job upload_jobs file
  template:
    src: upload_jobs.yaml.j2
    dest: /home/{{ username }}/jenkins/jobs/upload_jobs.yaml

- name: Copy jenkins job global file
  template:
    src: project.yaml.j2
    dest: /home/{{ username }}/jenkins/jobs/project.yaml

- name: Copy jenkins job global file
  template:
    src: global.yaml.j2
    dest: /home/{{ username }}/jenkins/jobs/global.yaml

- name: Copy jenkins job view file
  template:
    src: view.yaml.j2
    dest: /home/{{ username }}/jenkins/jobs/view.yaml

- name: Copy jenkins job ini file
  template:
    src: uploader.ini.j2
    dest: /home/{{ username }}/jenkins/uploader.ini

- name: Copy grid-router quota xml file
  template:
    src: razmik.xml.j2
    dest: /home/{{ username }}/grid-router/quota/razmik.xml

- name: Copy grid-router users password
  template:
    src: users.htpasswd.j2
    dest: /home/{{ username }}/grid-router/users.htpasswd

- name: Create browsers.json file
  template:
    src: browsers.json.j2
    dest: /home/{{ username }}/grid-router/browsers.json
  vars:
    chrome_version: "{{ browsers_versions.chrome }}"
    firefox_version: "{{ browsers_versions.firefox }}"

- name: Copy nginx selenoid.conf file to remote server
  template:
    src: selenoid.conf.j2
    dest: /home/{{ username }}/nginx/selenoid.conf

- name: Copy docker-compose.yml template to remote server
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ username }}/docker-compose.yml